apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        tier: frontend-nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80